name: "Integrate Release"
# Integrate release runs in the base repo
# when it receives a pull request
#
# This workflow only needs to be configured 
# by the base (upstream) fairground.
#
# See: https://www.appfair.net
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: fair-ground/Fair/.github/workflows/fair.yml@main
    secrets: inherit
    with:
      fairground: appfair
      target_macos: true
      target_linux: false
      target_windows: false
      target_ios: true
      target_tvos: false
      target_watchos: false
      fairseal_issuer: appfairbot
      license: AGPL-3.0

