name: "Integrate Release"
# Integrate release runs in the base repo
# when it receives a pull request
#
# This workflow only needs to be configured 
# by the base (upstream) fairground.
#
# See: https://www.appfair.net
on:
  pull_request_target:
    branches: [ main ]
    types: [opened, reopened]

jobs:
  call-workflow:
    uses: appfair/fairground/.github/workflows/fair.yml@main
    secrets: inherit
    with:
      fairseal_issuer: appfairbot
